### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by ajermakovics** [ajermakovics/jvm-mon#1]
Should be a matter of adding the right J2V8 dependency

**Comment by ajermakovics** [comment]
Should be fixed by #10

**Comment by ndhar-sumo** [comment]
@ajermakovics I think this issue is still there in latest release (4.8) of J2V8 - UnsatisfiedLinkError: Could not load J2V8 library. Reasons: no j2v8_linux_x86_64 in java.library.path ?

**Comment by ajermakovics** [comment]
Hi @ndhar-sumo ,
There's a new version of jvm-mon that is rewritten in Go and no longer uses j2v8. 
Unfortunately I'm not a windows user so haven't tested if it works.
